### ISSUE TITLE
repository set up and structure

### ISSUE THREAD

**Issue by aducrot** [EPFL-SV-cpp-projects/Team_4#1]

**Comment by ygrimault** [comment]
Right now, your project fails to compile, so I can't validate the task. If you have things in your make files that are set for the future, try to comment them instead, so that it can compile for now.
Moreover, try to have a project that does a little bit of something, for example a simple output that says "Hello world !".

**Comment by antjak** [comment]
I created a small "Hello World!" program and a basic unit test so you can validate the task, the project should compile now.

**Comment by ygrimault** [comment]
Everything's in order =) See you on Monday !
